### ISSUE TITLE
Definition of "slug" not sufficient

### ISSUE THREAD

**Issue by verdammelt** [exercism/generic-snippet-extractor#7]
The Common Lisp track's slug is `common-lisp` so I created a `common-lisp.txt` file and `common-lisp_test.rb` file (which used a `:common_lisp` argument in the assertion line because `:common-lisp` was obviously not going to work for Ruby.

First Rubocop failed because `common-lisp_test.rb` must be in snake case.

Then the tests failed because no file `commonlisp.txt` was found.

After renaming things so I had files `commonlisp.txt`, `commonlisp_test.rb` (with `:commonlisp` as argument in the assertion) the CI is happy.

**Comment by verdammelt** [comment]
Note: I will create a PR in a moment to (hopefully) fix this problem.

**Comment by iHiD** [comment]
Hmm. I'll fix this :) Sorry!

**Comment by verdammelt** [comment]
Looks like this was addressed so closing.
